# Rename this file to languages.toml to enable multilingual support
[en]
    languageName      = "English"
    languagedirection = "ltr"
    title             = "-Andreas_ | Xinxiao Wang"
    weight            = 1
[zh]
    languageName      = "简体中文"
    languagedirection = "ltr"
    title             = "-Andreas_ | 王歆逍"
    weight            = 2
